<script setup>
import { marked } from 'marked'
import { computed, ref } from 'vue'
import { parseSpiders } from '../sites.js'

const props = defineProps({
  items: { type: Array, default: () => [] },
})

const openId = ref(null)
// Filter state: which day and which official website the user wants to see.
const filterDate = ref('')
const filterSource = ref('')

// Unique official websites present across all loaded reports — drives the
// "按官网筛选" dropdown. Each report's `spiders` is a comma-joined list of
// crawler names; we split + map them to friendly labels.
const availableSources = computed(() => {
  const map = new Map()
  for (const r of props.items) {
    for (const s of parseSpiders(r.spiders)) {
      if (!map.has(s.key)) map.set(s.key, s)
    }
  }
  return [...map.values()].sort((a, b) => a.label.localeCompare(b.label, 'zh'))
})

const filtered = computed(() => {
  return props.items.filter((r) => {
    if (filterDate.value && r.date !== filterDate.value) return false
    if (filterSource.value && !(r.spiders || '').includes(filterSource.value)) return false
    return true
  })
})

function sitesOf(r) {
  return parseSpiders(r.spiders)
}

function render(md) {
  return marked.parse(md || '', { breaks: true })
}

function resetFilters() {
  filterDate.value = ''
  filterSource.value = ''
}
</script>

<template>
  <div>
    <!-- Filter bar: pick a day and/or an official website. -->
    <div class="filters">
      <label>
        日期
        <input type="date" v-model="filterDate" />
      </label>
      <label>
        官网
        <select v-model="filterSource">
          <option value="">全部</option>
          <option v-for="s in availableSources" :key="s.key" :value="s.key">
            {{ s.label }}
          </option>
        </select>
      </label>
      <button class="reset" @click="resetFilters">重置</button>
      <span class="count">{{ filtered.length }} 条报告</span>
    </div>

    <p v-if="!filtered.length" class="empty">暂无符合条件的报告。</p>
    <div v-for="r in filtered" :key="r.id" class="card">
      <div class="head" @click="openId = openId === r.id ? null : r.id">
        <div class="title-wrap">
          <strong>{{ r.title }}</strong>
          <div class="chips">
            <span class="date">{{ r.date || '未知日期' }}</span>
            <a
              v-for="s in sitesOf(r)"
              :key="s.key"
              class="chip"
              :href="s.home || '#'"
              target="_blank"
              rel="noopener"
              @click.stop
            >{{ s.label }}</a>
          </div>
        </div>
        <span class="chev">{{ openId === r.id ? '▲' : '▼' }}</span>
      </div>
      <!-- Content is generated by our own DeepSeek pipeline (trusted); in a
           multi-tenant deployment add DOMPurify before v-html. -->
      <div v-if="openId === r.id" class="body" v-html="render(r.content_md)"></div>
    </div>
  </div>
</template>

<style scoped>
.filters {
  display: flex;
  align-items: center;
  gap: 12px;
  flex-wrap: wrap;
  margin-bottom: 14px;
  font-size: 13px;
  color: var(--muted);
}
.filters label {
  display: flex;
  align-items: center;
  gap: 6px;
}
.filters input,
.filters select {
  font-size: 13px;
  padding: 5px 8px;
  border: 1px solid var(--border);
  border-radius: 6px;
  background: var(--card);
  color: var(--text);
}
.reset {
  border: 1px solid var(--border);
  background: transparent;
  color: var(--muted);
  border-radius: 6px;
  padding: 5px 10px;
  cursor: pointer;
}
.count {
  margin-left: auto;
}
.card {
  background: var(--card);
  border: 1px solid var(--border);
  border-radius: 10px;
  margin-bottom: 12px;
  overflow: hidden;
}
.head {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 12px 14px;
  cursor: pointer;
  font-size: 14px;
}
.head:hover {
  background: #f7fafc;
}
.title-wrap {
  display: flex;
  flex-direction: column;
  gap: 6px;
}
.chips {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
  align-items: center;
}
.date {
  color: var(--muted);
  font-size: 12px;
}
.chip {
  font-size: 12px;
  color: var(--accent);
  background: #e8f1fb;
  border-radius: 999px;
  padding: 2px 10px;
  text-decoration: none;
}
.chip:hover {
  background: #d6e7f8;
}
.chev {
  color: var(--muted);
  font-size: 12px;
}
.body {
  padding: 0 16px 14px;
  font-size: 13px;
  line-height: 1.7;
  border-top: 1px solid var(--border);
  padding-top: 12px;
}
.empty {
  color: var(--muted);
  font-size: 14px;
}
</style>
